### PR TITLE
Updated CSS and Site with latest colors and logo

### PR DESCRIPTION
**Pull request by rasummer**
@jsuereth @eed3si9n 

Hey Josh, Eugene. I've updated the sbt site to use the new logo. I've also styled the site so it's a little more inline from a color and font weight perspective. Please be kind enough to review and let me know if I've missed anything. 

Rich

### CODE REVIEW

**Comment by eed3si9n** [comment]
The source for the website is on sbt/website.

**Comment by rasummer** [comment]
@eed3si9n 

I don't need to change the source correct? I was simply changing CSS and adding images, which I thought came from this repo. Any guidance would be helpful? Thanks Rich

**Comment by eed3si9n** [comment]
sbt's website is generated using nanoc and pamflet using files in sbt/website except for API docs.

See
- https://github.com/sbt/website/tree/master/src/nanoc/content
- https://github.com/sbt/website/tree/master/src/tutorial
- https://github.com/sbt/website/tree/master/src/reference

**Comment by rasummer** [comment]
@eed3si9n  Thanks for pointing me in the right direction ;)

**Comment by benmccann** [comment]
@eed3si9n The README on this project only points to sbt/sbt. Perhaps it should also point to sbt/website?

**Comment by eed3si9n** [comment]
Yes. I should update the README.

**Comment by eed3si9n** [comment]
closing this PR tho.

**Comment by eed3si9n** [comment]
Updated the README: 32007d7c5d48c54e3f09a723a7307a677699981c

**Pull request closed without merging**
